### ISSUE TITLE
Resizing doesn't work if expanding a region

### ISSUE THREAD

**Issue by SenPr** [WhipDevelopment/CrashClaim#28]
When you try to resize, specifically expanding a claim, it does absolutely nothing.

I'm looking into this, and the code I think that is causing this issue is in ClaimDataManager.java where a new ConfirmationMenu is created, but the BiFunction is not running strangely? Thus it does not get processed properly.

Trying to fix it on a fork myself, but hoping if anyone else can replicate the issue or find a fix.

EDIT: Should also note, that I am using the CrashClaimEconomy addon as well

**Comment by SenPr** [comment]
Might have found the fix, it is running ConfirmationMenu.initialize() which does nothing.
Other places that used ConfirmationMenu used .open()

**Comment by DaJokni** [comment]
i can reproduce this bug, making the claim smaller does work but making it bigger doesnt

and i can also confirm that what you said does fix it, will you open a pr with that fix?

**Comment by SenPr** [comment]
yeah I will eventually, need to make a separate branch, since I also added a bunch of other stuff for myself

**Comment by SenPr** [comment]
> i can reproduce this bug, making the claim smaller does work but making it bigger doesnt
> 
> and i can also confirm that what you said does fix it, will you open a pr with that fix?

So I was gonna make a PR, but apparently the original code is correct lol
It was your fork that made the mistake, I will close this issue
