### ISSUE TITLE
Claim tool

### ISSUE THREAD

**Issue by DeltaR4v0x** [WhipDevelopment/CrashClaim#32]
Hi, it's possible to add a claim tool? Left or right click for directly claim and other click for info in this chunk

**Comment by SenPr** [comment]
just use griefprevention at that point lol

CrashClaim design is made to be simple, with no tools required. Tho I do admit there is currently no way to check current claim info.

**Comment by Log1x** [comment]
You can use https://github.com/CreativeCraft/CrashClaimUtilities for claim info, etc.

**Edit**: Well I guess not a traditional claim info (sorry its been awhile) – would be easy to add though.

**Comment by DeltaR4v0x** [comment]
SenPr I suspect it but GP really sucks for my part I like Crashclaim.

Log1x thx i go try it
