### ISSUE TITLE
Mob Damage In Claims

### ISSUE THREAD

**Issue by Pandas0** [WhipDevelopment/CrashClaim#7]
By default users cannot hit/kill entities in other player's claims, this causes an issue due to the entities still being able to kill the players. My suggestion is to have the Entity flag to be enabled by default.

**Comment by Chasewhip8** [comment]
In future versions, you will be able to configure this yourself, for this case I think claims should be fully protected upon creation so the default config will stay like this.

**Comment by conflictxinside** [comment]
Having the same issue.  This should be able to be disabled on a server-level so players CAN'T enable it.
