### ISSUE TITLE
Entities In Claims

### ISSUE THREAD

**Issue by Pandas0** [WhipDevelopment/CrashClaim#8]
All claim settings seem to effect entities as well. My players are reporting that sheep cannot eat grass and animals cannot use pressure plates while in a claim.

I believe the only entities that should be effected by default are creepers, enderman, and such that do actual damage to the claims.

**Comment by Chasewhip8** [comment]
Claims are fully protected by default you need to enable mob griefing in order to allow sheep to eat grass, as for the pressure plate thing people can lure sheep into other people's claims and press them so that's not ideal.

**Comment by ReportCardsMC** [comment]
Will it ever be possible to enable specific mob griefing things such as sheep eating grass? Would love to see it in claims with sheep farms

**Comment by KieranBeals** [comment]
yes something like this but in a setting that defaults to true in advanced settings
